name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches: ["main"] # 当推送到 main 分支时触发
  workflow_dispatch: # 允许你在 GitHub 网页上手动触发流水线

# 授权 GitHub Actions 将文件部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 确保同一时间只有一个部署在运行
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies and Build
        run: |
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # ✨ Vite 默认的打包产物目录

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # 必须等 build 任务完成后才执行部署
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
